# Generated by Django 4.0.6 on 2022-07-30 10:07

import ckeditor.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(blank=True, max_length=60, null=True)),
                ('client_contact', models.CharField(blank=True, max_length=80, null=True)),
                ('client_phone', models.CharField(blank=True, max_length=16, null=True, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{8,15}$')])),
                ('client_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('venue', models.CharField(blank=True, max_length=50, null=True)),
                ('venue_contact', models.CharField(blank=True, max_length=80, null=True)),
                ('venue_phone', models.CharField(blank=True, max_length=16, null=True, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{8,15}$')])),
                ('venue_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('event_manager', models.CharField(max_length=60)),
                ('event_type_dinner_etc', models.CharField(blank=True, max_length=100, null=True)),
                ('event_planner', models.CharField(max_length=60)),
                ('guest_num', models.PositiveIntegerField(blank=True, null=True)),
                ('food_leaves', models.TimeField(blank=True, null=True)),
                ('chefs_leave', models.TimeField(blank=True, null=True)),
                ('porters_leave', models.TimeField(blank=True, null=True)),
                ('total_waiters', models.PositiveIntegerField(blank=True, null=True)),
                ('dietaries', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('food_arrive', models.TimeField(blank=True, null=True)),
                ('chefs_arrive', models.TimeField(blank=True, null=True)),
                ('porter_arrives', models.TimeField(blank=True, null=True)),
                ('total_chefs', models.PositiveIntegerField(blank=True, null=True)),
                ('menu', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('staff_food', models.CharField(blank=True, max_length=100, null=True)),
                ('drinks_garnishes', models.CharField(blank=True, max_length=100, null=True)),
                ('druggett_and_tape', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Furniture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_header', models.CharField(blank=True, choices=[('t', 'TABLES'), ('tl', 'TABLE LINEN'), ('n', 'NAPKINS'), ('d', 'DISPOSABLE NAPKINS')], max_length=20)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('supplied_by', models.CharField(blank=True, max_length=70, null=True)),
                ('location_purpose', models.CharField(blank=True, max_length=70, null=True)),
                ('blank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blank.blank')),
            ],
        ),
        migrations.CreateModel(
            name='BlankMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timings', models.DateField(blank=True, null=True)),
                ('action', models.CharField(blank=True, max_length=120, null=True)),
                ('blank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blank.blank')),
            ],
        ),
    ]
